### ISSUE TITLE
[이슈]

### ISSUE THREAD

**Issue by Wisdom-Kim** [gntodtndls156/SAIT-TeamProject#1]
* 이슈 양식 작성 전 임의로 올립니다

혹시 실습 때 배운 gitmoji 사용해보는거 어떻게 생각하세요?.?

**Comment by liminaire-x** [comment]
이슈 양식 작성 되었으므로 이슈 재개시 부탁드리오며, 혹은 다시 열고 질문하시길 바랍니다.

Commit: [3a20a2c](https://github.com/gntodtndls156/SAIT-TeamProject/commit/3a20a2c761bb6df18a2c8a0b25a735c5ec116cc6)

이동: #2
