### ISSUE TITLE
이슈 템플릿 적용 전 작성한 이슈의 템플릿 양식 적용

### ISSUE THREAD

**Issue by Wisdom-Kim** [gntodtndls156/SAIT-TeamProject#2]
## 제목

이슈 템플릿 적용 전 작성한 이슈의 템플릿 양식 적용

### 설명

> 이슈에 대해 요약 설명

이슈 템플릿 반영 전 게시한 이슈는, 수정을 시도해도 새로 설정한 이슈 템플릿이 뜨지 않습니다.
이슈 템플린 반영 이후에 게시한 이슈에 대해서만 양식이 뜨는 것 같습니다.

#### 참고 자료 (선택사항)
#1

**Comment by liminaire-x** [comment]
확인했습니다! 수고하셨습니다.

**Comment by Wisdom-Kim** [comment]
확인해보니 이슈 템플릿 적용시, 적용 이후 새 글을 작성할 때만 양식이 반영되는 것 같습니다.
프로젝트 초기에 이슈 템플릿, 커밋 컨벤션 등 규칙을 미리미리 설정하는게 중요하군요!
