### ISSUE TITLE
git push 에러 발생

### ISSUE THREAD

**Issue by hj613** [gntodtndls156/SAIT-TeamProject#3]
## 제목
git push 에러 발생

### 설명
>
git push -u origin을 했더니 아래와 같이 오류가 발생하여 commit이 제대로 되지 않습니다. 해결 방법이 있을까요?

#### 참고 자료 (선택사항)
![issue](https://github.com/gntodtndls156/SAIT-TeamProject/assets/163812603/e74b2a74-a311-49b1-af80-463e96f05bfb)

**Comment by liminaire-x** [comment]
# 해결 방법
## 첫 번째

```shell
git pull
```
저장소에서 최신 커밋 내용을 불러오고 충돌 발생한 파일을 수정하거나 합친 후

```shell
git commit
git push
```
를 진행하면 해결할 수 있습니다.

## 두 번째

아래 코드를 실행하기 전에, **정말로** 지금까지 진행한 개발 내용이 지워져도 상관없는 경우 실행하길 바랍니다.
```shell
git reset --hard HEAD
git pull
```

**Comment by hj613** [comment]
알려주신 방법대로 진행하니 해결되었습니다 감사합니다!
