### ISSUE TITLE
로그인 UI에서 비밀번호 노출

### ISSUE THREAD

**Issue by Wisdom-Kim** [gntodtndls156/SAIT-TeamProject#4]
## 제목

로그인 UI에서 비밀번호 노출

### 설명

> 이슈에 대해 요약 설명

비밀번호를 입력하는 UI에서 비밀번호가 노출이 다 되버립니다.
이러면 비밀번호가 다 보여서 보안에 안 좋을 것 같습니다..

#### 참고 자료 (선택사항)
Commit:[b8cd9da](https://github.com/gntodtndls156/SAIT-TeamProject/commit/b8cd9da1119a1737b02c5ee0571db0f7a79a2364)

**Comment by liminaire-x** [comment]
조만간 @hj613 님께서 해결하실 것입니다. 잠시만 기다려 주세요~

**Comment by Wisdom-Kim** [comment]
확인했습니다. 감사합니다!
